### ISSUE TITLE
test 파일 작성

### ISSUE THREAD

**Issue by Dh3356** [Dh3356/projectA#1]
## Description
프로젝트 시작 전에 앞서 테스트 파일 작성

### A.txt 작성
- [x] A.txt

### Additional context
테스트용 파일이므로 추후 삭제 예정

**Comment by zelkovaria** [comment]
파일 본문 수정해주세요

**Comment by Dh3356** [comment]
A.txt로 하고 본문은 likelion으로 하겠습니다.
